const wordData = [
  { word: "逛", meaning: "to stroll; to browse (shops/market)", example: "我們週末去逛夜市。(We’ll stroll around the night market on the weekend.)" },
  { word: "忽然", meaning: "suddenly", example: "天氣忽然下雨了。(It suddenly started to rain.)" },
  { word: "小吃", meaning: "snack; street food", example: "這條街有很多台灣小吃。(There are many Taiwanese street foods on this street.)" },
  { word: "出口", meaning: "exit", example: "地鐵三號出口在右邊。(Exit 3 of the metro is on the right.)" },
  { word: "剛", meaning: "just; a short while ago", example: "我剛到學校。(I just arrived at school.)" },
  { word: "姓", meaning: "surname; family name", example: "請問您貴姓？(May I ask your family name?)" },
  { word: "就", meaning: "then; right away; as early as", example: "他說到就做到。(He does it right away once he says it.)" },
  { word: "各", meaning: "each; every", example: "各位同學請坐好。(Everyone, please be seated.)" },
  { word: "殺價", meaning: "to bargain; to haggle", example: "在市場可以試著殺價。(You can try to bargain at the market.)" },
  { word: "招牌", meaning: "signboard; signature (dish/product)", example: "這家店的招牌是牛肉麵。(The shop’s signature dish is beef noodles.)" },
  { word: "遊客", meaning: "tourist; visitor", example: "這裡週末有很多遊客。(There are many tourists here on weekends.)" },
  { word: "豆腐", meaning: "tofu", example: "她常做麻婆豆腐。(She often makes mapo tofu.)" },
  { word: "炸", meaning: "to deep-fry; fried", example: "他最愛吃炸雞。(He loves to eat fried chicken.)" },
  { word: "雞排", meaning: "chicken cutlet", example: "我想點一份雞排。(I’d like to order a chicken cutlet.)" },
  { word: "香", meaning: "fragrant; tasty; aromatic", example: "這碗麵好香。(This bowl of noodles smells great.)" },
  { word: "習慣", meaning: "habit; to be used to", example: "我不習慣這麼早起床。(I’m not used to getting up so early.)" },
  { word: "糖", meaning: "sugar", example: "飲料要不要加糖？(Do you want to add sugar to the drink?)" },
  { word: "選", meaning: "to choose; select", example: "你可以自己選口味。(You can choose the flavor yourself.)" },
  { word: "無", meaning: "no; none; without", example: "這杯是無糖的。(This drink is sugar-free.)" },
  { word: "加", meaning: "to add", example: "請幫我加一點湯。(Please add a little soup for me.)" },
  { word: "冰塊", meaning: "ice cubes", example: "我要少冰塊。(I’d like fewer ice cubes.)" },
  { word: "推薦", meaning: "to recommend; recommendation", example: "你有推薦的餐廳嗎？(Do you have a restaurant recommendation?)" },
  { word: "辣", meaning: "spicy; hot (taste)", example: "我怕辣。(I can’t handle spicy food.)" },
  { word: "酸", meaning: "sour", example: "這道菜有點酸。(This dish is a bit sour.)" },
  { word: "鹹", meaning: "salty", example: "湯太鹹了。(The soup is too salty.)" },
  { word: "苦", meaning: "bitter", example: "中藥有點苦。(Chinese medicine tastes a bit bitter.)" },
  { word: "聞", meaning: "to smell; to sniff", example: "你聞到了嗎？很香。(Did you smell it? It’s aromatic.)" },
  { word: "討厭", meaning: "to dislike; annoying", example: "我討厭抽菸的味道。(I dislike the smell of cigarettes.)" },
  { word: "其實", meaning: "actually; in fact", example: "我其實不太餓。(I’m actually not very hungry.)" },
  { word: "試", meaning: "to try; to taste", example: "你可以先試一口。(You can try a bite first.)" },
  { word: "臭豆腐", meaning: "stinky tofu", example: "他第一次吃臭豆腐。(He tried stinky tofu for the first time.)" },
  { word: "蚵仔煎", meaning: "oyster omelet", example: "夜市的蚵仔煎很好吃。(The oyster omelet at the night market is delicious.)" },
  { word: "特別", meaning: "special; especially; unusual", example: "這家店的味道很特別。(The flavor at this shop is special.)" }
];
